name: "Builds"

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-all:
   uses: ./.github/workflows/shared-build.yml
   permissions:
     contents: read
   with:
      environment: 'testing'

  # Initially create a release with 1 job
  # so multiple files can be uploaded at the same time afterwards
  create-release:
    if: github.event_name != 'pull_request' && github.ref_name == 'main'
    runs-on: ubuntu-24.04
    environment: 'testing'
    needs: [build-all]
    permissions:
      contents: write
    outputs:
      tag_name: ${{ steps.meta.outputs.tag_name }}

    steps:
    - name: Release tag
      id: meta
      run: echo "tag_name=dev-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

    - name: Release
      uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
      with:
        prerelease: true
        make_latest: false
        name: 'dev-${{ github.sha }}'
        tag_name: ${{ steps.meta.outputs.tag_name }}
        target_commitish: ${{ github.sha }}

  deploy-release:
    if: github.event_name != 'pull_request' && github.ref_name == 'main'
    strategy:
      matrix:
        target_os: [
          'linux-amd64',
          'linux-i686',
          'linux-arm64',
          'linux-armhf',
          'linux-powerpc',
          'linux-ppc64',
          'linux-ppc64el',
          'windows-x64-pdb',
          'windows-x86-pdb',
          'windows-arm64-pdb',
        ]

    runs-on: ubuntu-24.04
    environment: 'testing'
    needs: [create-release]
    permissions:
      contents: write

    env:
      RELEASE_NAME: ${{github.event.repository.name}}-dev-${{matrix.target_os}}
      RELEASE_TAG: ${{ needs.create-release.outputs.tag_name }}

    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: 'out-${{matrix.target_os}}'
        path: ${{github.workspace}}/${{matrix.target_os}}

    - name: Zip
      working-directory: '${{github.workspace}}/${{matrix.target_os}}'
      run: zip -9 -r "../${{env.RELEASE_NAME}}.zip" ./

    - name: Release
      uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        make_latest: false
        files: ${{github.workspace}}/${{env.RELEASE_NAME}}.zip
